name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: "1.24.4"
  BINARY_NAME: btwarch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
            -ldflags="-s -w -X main.version=${{ github.sha }}" \
            -o ${{ env.BINARY_NAME }}_linux_amd64 \
            ./cmd/app/main.go

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.REMOTE_HOST }}
          SSH_USER: ${{ secrets.REMOTE_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat > ~/.ssh/config <<EOF
          Host $SSH_HOST
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
          EOF

          DEPLOY_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          ssh $SSH_USER@$SSH_HOST << 'ENDSSH'
            mkdir -p ~/btwarch/{backups,database/migrations}
            chmod 755 ~/btwarch ~/btwarch
          ENDSSH

          ssh $SSH_USER@$SSH_HOST << 'ENDSSH'
            if [ -f ~/btwarch/btwarch_linux_amd64 ]; then
              cp ~/btwarch/btwarch_linux_amd64 ~/btwarch/backups/btwarch_linux_amd64.backup.$DEPLOY_TIMESTAMP
            fi
          ENDSSH

          scp ${{ env.BINARY_NAME }}_linux_amd64 $SSH_USER@$SSH_HOST:~/btwarch/
          ssh $SSH_USER@$SSH_HOST "chmod +x ~/btwarch/btwarch_linux_amd64"

          if [ -d "database/migrations" ]; then
            scp -r database/migrations/* $SSH_USER@$SSH_HOST:~/btwarch/database/migrations/
          fi

          ssh $SSH_USER@$SSH_HOST << 'ENDSSH'
            sudo systemctl stop btwarch || true
            sleep 5

            sudo systemctl start btwarch
            sleep 5

            if ! sudo systemctl is-active --quiet btwarch; then
              echo "Service failed to start. Checking logs..."
              sudo journalctl -u btwarch -n 50 --no-pager
              exit 1
            fi

            for i in {1..6}; do
              if curl -sf http://localhost:8080/health; then
                echo "Health check passed"
                break
              fi
              if [ $i -eq 6 ]; then
                echo "Health check failed after multiple attempts"
                exit 1
              fi
              echo "Waiting for service to be ready..."
              sleep 5
            done
          ENDSSH

          rm -f ~/.ssh/deploy_key ~/.ssh/config

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Deployment completed successfully"
          else
            echo "❌ Deployment failed"
          fi
