name: Healthcheck

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Healthcheck
        run: |
          curl -s http://api.btwarch.me/health | grep -q "OK"
